### ISSUE TITLE
Argument 2 passed to NewRelic\Middleware\NameTransactionMiddleware::__invoke() must be an instance of Cake\Http\Client\Response

### ISSUE THREAD

**Issue by burzum** [brunitto/cakephp-new-relic#10]
I'm getting this error message for the new 1.3 release:

> Argument 2 passed to NewRelic\Middleware\NameTransactionMiddleware::__invoke() must be an instance of Cake\Http\Client\Response, instance of Cake\Http\Response given, called in C:\xampp\htdocs\WA3\vendor\cakephp\cakephp\src\Http\Runner.php on line 65

I'm pretty sure this should be Cake\Http\Response in the plugin.

**Comment by rodrigorm** [comment]
Wich version of CakePHP are you using?

**Comment by nabilacoutinho** [comment]
Hey @rodrigorm, I had the same problem after upgrade to CakePHP 3.6

**Comment by rodrigorm** [comment]
Ok, let me check.

**Comment by rodrigorm** [comment]
Added a PR to fix this problem.

**Comment by brunitto** [comment]
Ops, my bad. I am working in the PR right now.

**Comment by brunitto** [comment]
Just merged the PR and created the 1.3.1 version. Thanks @burzum @nabilacoutinho and @rodrigorm .
